### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by visualcookie** [anarh/node-sass-import#1]
package.json
```
{
  "name": "baukasten",
  "version": "0.1.0",
  "description": "Baukasten is a super thin boilerplate with only the basic stuff.",
  "scripts": {
    "sass": "node-sass --include-path scss assets/scss/main.scss assets/css/main.css --importer node_modules/node-sass-import",
    "prefix": "postcss --use autoprefixer -o assets/css/main.css assets/css/main.css",
    "build": "npm run sass && npm run prefix",
    "watch": "nodemon -e scss -x npm run build"
  },
  "keywords": [
    "boilerplate",
    "sass",
    "frontend"
  ],
  "author": "Dean Hidri",
  "license": "WTFPL",
  "devDependencies": {
    "autoprefixer": "^6.3.6",
    "bemify": "^0.1.2",
    "node-sass": "^3.6.0",
    "node-sass-import": "^1.0.0",
    "nodemon": "^1.9.1",
    "postcss-cli-simple": "^1.0.1",
    "sass-module-importer": "^1.2.1",
    "sass-rem": "^1.2.2"
  }
}
```

Console Log:
```
G:\work\development\_github\baukasten\node_modules\node-sass-import\lib\node-sass-import.js:19
    if (err) throw err;
             ^

Error: Cannot find module 'sass-rem' from 'G:/work/development/_github/baukasten/assets/scss'
    at G:\work\development\_github\baukasten\node_modules\resolve\lib\async.js:46:17
    at process (G:\work\development\_github\baukasten\node_modules\resolve\lib\async.js:173:43)
    at ondir (G:\work\development\_github\baukasten\node_modules\resolve\lib\async.js:188:17)
    at load (G:\work\development\_github\baukasten\node_modules\resolve\lib\async.js:69:43)
    at onex (G:\work\development\_github\baukasten\node_modules\resolve\lib\async.js:92:31)
    at G:\work\development\_github\baukasten\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by anarh** [comment]
Hey @visualcookie 

Try this (I basically removed the include-path option.)

    "sass": "node-sass assets/scss/main.scss assets/css/main.css --importer node_modules/node-sass-import",

**Comment by visualcookie** [comment]
Nice, seems to be working. You have to change the doc then. :+1:
